### ISSUE TITLE
Add ability to customize CONTINUATION_TOKEN_QUERY_PARAM

### ISSUE THREAD

**Issue by abeag** [davidepedone/spring-cursor-pagination#1]
Hi Davide,

"spring-cursor-pagination-hateoas" is very useful.
But unfortunately looks like CONTINUATION_TOKEN_QUERY_PARAM is hardcoded to "continuationToken".
Could you please add an ability to customize it.
For example, for Spring and Spring Hateoas it can be done something like this.

```
@Configuration
public class PageableConfig {

    @Bean
    PageableHandlerMethodArgumentResolverCustomizer pageableResolverCustomizer() {
        return r -> {
            r.setSizeParameterName("pageLimit");
            r.setPageParameterName("pageCursor");
        };
    }
}
```

Regards Alexander

**Comment by davidepedone** [comment]
Thank you Alexander, I'm working on it ;)
